services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql-database
    ports:
      - 8080:8080
    volumes:
      - ./log:/home/bringauto/log/
    networks:
      - api-network
    command: ["config/config.json", "--location", "postgresql-database"]

  postgresql-database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: test_management_api
    networks:
      - api-network
    ports:
      - 5432:5432

networks:
  api-network:
