version: '3.0'

services:
  FleetBackend:
    image: fleet-backend
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - bring-emulator

  database:
    image: postgres:12.15
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=BringAutoRules2023!
      - POSTGRES_USER=fleet
    networks:
      - bring-emulator

networks:
  bring-emulator:
    external:
      name: bring-emulator