from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from fleet_management_api.models.base_model import Model
from fleet_management_api import util


class CarActionStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NORMAL = 'normal'
    PAUSED = 'paused'
    def __init__(self):  # noqa: E501
        """CarActionStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CarActionStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CarActionStatus of this CarActionStatus.  # noqa: E501
        :rtype: CarActionStatus
        """
        return util.deserialize_model(dikt, cls)
