openapi: 3.0.0
info:
  title: BringAuto Fleet Management v2 API
  description: Specification for BringAuto fleet backend HTTP API
  version: 1.1.0
  contact:
    name: BringAuto s.r.o
    url: https://bringauto.com
    email: fleet@bringauto.com
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html

servers:
  - url: /v2/management

security:
  - APIKeyAuth: []
  - oAuth2AuthCode: []

tags:
  - name: car
    description: Car related functions
  - name: carState
    description: Car state related functions
  - name: order
    description: Order related functions
  - name: orderState
    description: Order state related functions
  - name: platformHwId
    description: Platform hardware ID related functions
  - name: route
    description: Route state related functions
  - name: stop
    description: Stop state related functions
  - name: security
    description: Authentication related functions

paths:
  /car:
    $ref: 'car.yaml#/paths/~1car'
  /car/{carId}:
    $ref: 'car.yaml#/paths/~1car~1{carId}'
  /carstate:
    $ref: 'car.yaml#/paths/~1carstate'
  /carstate/{carId}:
    $ref: 'car.yaml#/paths/~1carstate~1{carId}'

  /order:
    $ref: 'order.yaml#/paths/~1order'
  /order/{orderId}:
    $ref: 'order.yaml#/paths/~1order~1{orderId}'
  /order/wait/{carId}:
    $ref: 'order.yaml#/paths/~1order~1wait~1{carId}'
  /orderstate:
    $ref: 'order.yaml#/paths/~1orderstate'
  /orderstate/{orderId}:
    $ref: 'order.yaml#/paths/~1orderstate~1{orderId}'

  /platformhwid:
    $ref: 'platform_hw_id.yaml#/paths/~1platformhwid'
  /platformhwid/{platformhwidId}:
    $ref: 'platform_hw_id.yaml#/paths/~1platformhwid~1{platformhwidId}'

  /route:
    $ref: 'route.yaml#/paths/~1route'
  /route/{routeId}:
    $ref: 'route.yaml#/paths/~1route~1{routeId}'
  /routepoints:
    $ref: 'route.yaml#/paths/~1routepoints'
  /routepoints/{routeId}:
    $ref: 'route.yaml#/paths/~1routepoints~1{routeId}'

  /stop:
    $ref: 'stop.yaml#/paths/~1stop'
  /stop/{stopId}:
    $ref: 'stop.yaml#/paths/~1stop~1{stopId}'

  /login:
    $ref: 'security.yaml#/paths/~1login'
  /token_get:
    $ref: 'security.yaml#/paths/~1token_get'
  /token_refresh:
    $ref: 'security.yaml#/paths/~1token_refresh'

components:
  securitySchemes:
    APIKeyAuth:
      $ref: 'security.yaml#/components/securitySchemes/APIKeyAuth'
    oAuth2AuthCode:
      $ref: 'security.yaml#/components/securitySchemes/oAuth2AuthCode'