from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class MobilePhone(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, phone=None):  # noqa: E501
        """MobilePhone - a model defined in OpenAPI

        :param phone: The phone of this MobilePhone.  # noqa: E501
        :type phone: str
        """
        self.openapi_types = {
            'phone': str
        }

        self.attribute_map = {
            'phone': 'phone'
        }

        self._phone = phone

    @classmethod
    def from_dict(cls, dikt) -> 'MobilePhone':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MobilePhone of this MobilePhone.  # noqa: E501
        :rtype: MobilePhone
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phone(self) -> str:
        """Gets the phone of this MobilePhone.


        :return: The phone of this MobilePhone.
        :rtype: str
        """
        return self._phone

    @phone.setter
    def phone(self, phone: str):
        """Sets the phone of this MobilePhone.


        :param phone: The phone of this MobilePhone.
        :type phone: str
        """

        self._phone = phone
